### PR TITLE
setup page CSS

### PR DESCRIPTION
**Pull request by AnthonyGaimari**
Ann this is the setup of the style.css page please review then push.

### CODE REVIEW

**Comment by anncoleman3** [comment]
Great Tony, thank you!

   I’ll be able to take a look around 4:30 and keep you in the loop!

-Anne Coleman

**Comment by AnthonyGaimari** [comment]
Hi Anne,


This pull request was a test from last night all I did was add the <h2> tag within the css see if you can see that change.

Small incremental changes are the best way to go thats all I was testing.


Warmest Regards,


Anthony Gaimari

**Comment by AnthonyGaimari** [comment]
Hi Anne,


I have created the results page and would like to share it with you before we get to class tomorrow OK?

Anytime before 7pm.

Can you do a google hang out? If so send me your google email.

I hope you like it.


Anthony Gaimari.

**Comment by anncoleman3** [comment]
Hello Anthony,

I do apologize as I'm just getting home from work. I will be on here
working tonight and can talk or meet from tomorrow 11:30am-12:15pm. I have
not used google hang out but I'll be happy to dive in and talk a look. I'll
also be there before office hours tomorrow too. Let me know if any of these
time work for you.

-Anne

**Pull request merged**
